name: Apply Migrations with Supabase CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Supabase CLI via Homebrew
      run: |
        # Устанавливаем Homebrew если нет
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        
        # Устанавливаем Supabase CLI
        brew install supabase/tap/supabase
        supabase --version

    - name: Apply migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Получаем информацию о проекте
        SUPABASE_PROJECT_ID=$(supabase projects list --json | jq -r '.[0].id')
        
        # Применяем миграции
        supabase db push --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD