name: Apply Migrations with Supabase CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/**'

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Supabase CLI via Homebrew
      run: |
        # Устанавливаем Homebrew если нет
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        
        # Устанавливаем Supabase CLI
        brew install supabase/tap/supabase
        supabase --version

    - name: Apply migrations with supabase db push
      env:
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        ### Вариант 1: Простое применение миграций
        npx supabase db push --db-url="$DB_URL" --debug
        
        ## Вариант 2: С предварительным dry-run (рекомендуется)
        # echo "=== DRY RUN ==="
        # supabase db push --db-url="$DB_URL" --dry-run
        
        # echo "=== APPLYING MIGRATIONS ==="
        # supabase db push --db-url="$DB_URL"
        
        # echo "=== MIGRATION COMPLETE ==="

    - name: Verify migrations
      env:
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        # Проверяем историю миграций
        npx supabase migration list --db-url="$DB_URL"