name: Apply Migrations with Supabase CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/**'

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Download and install Supabase CLI
      run: |
        # Скачиваем последнюю версию Supabase CLI
        LATEST_RELEASE=$(curl -s https://api.github.com/repos/supabase/cli/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        wget "https://github.com/supabase/cli/releases/download/${LATEST_RELEASE}/supabase_${LATEST_RELEASE:1}_linux_amd64.tar.gz"
        tar -xzf supabase_${LATEST_RELEASE:1}_linux_amd64.tar.gz
        sudo mv supabase /usr/local/bin/
        supabase --version

    - name: Apply migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Получаем информацию о проекте
        SUPABASE_PROJECT_ID=$(supabase projects list --json | jq -r '.[0].id')
        
        # Применяем миграции
        supabase db push --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD