name: Apply Migrations with Supabase CLI

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/migrations/**'
      - '.github/workflows/**'

jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Supabase CLI
      run: |
        # Устанавливаем Supabase CLI (официальный метод)
        curl -fsSL https://github.com/supabase/cli/raw/main/install.sh | bash
        sudo mv /home/runner/.supabase/bin/supabase /usr/local/bin/
        supabase --version

    - name: Apply migrations
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        # Получаем информацию о проекте
        SUPABASE_PROJECT_ID=$(supabase projects list --json | jq -r '.[0].id')
        
        # Применяем миграции
        supabase db push --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD